{
  "attachments": [],
  "avatar_url": "http://i.groupme.com/123456789",
  "created_at": 1302623328,
  "group_id": "25165949",
  "id": "1234567890",
  "name": "John",
  "sender_id": "12345",
  "sender_type": "user",
  "source_guid": "GUID",
  "system": false,
  "text": "Hello world ☃☃",
  "user_id": "1234567890"
}

{
  "attachments":[],
  "avatar_url":"https://i.groupme.com/1920x1920.jpeg.20366c2911304528b8932d312e750cac",
  "created_at":1475178987,
  "group_id":"25165949",
  "id":"147517898704414286",
  "name":"Robert Ross",
  "sender_id":"28758543",
  "sender_type":"user",
  "source_guid":"503fc29713be0ddf722ed71d84052b7b",
  "system":false,
  "text":"DAMN",
  "user_id":"28758543"
}

CHUNKS[0]:
{
  "attachments":[
    {
      "loci":[[0,12]],
      "type":"mentions",
      "user_ids":["28758543"]
    }
  ],
  "avatar_url":"https://i.groupme.com/1920x1920.jpeg.20366c2911304528b8932d312e750cac",
  "created_at":1475191285,
  "group_id":"25165949",
  "id":"147519128572277919",
  "name":"Robert Ross",
  "sender_id":"28758543",
  "sender_type":"user",
  "source_guid":"e941ca8b007c2d72baf33c4caf9fb59f",
  "system":false,
  "text":"@Robert Ross",
  "user_id":"28758543"
}

{ latitude: 32.4128,
  longitude: -81.7957,
  timezone: 'America/New_York',
  offset: -4,
  currently:
   { time: 1475372575,
     summary: 'Clear',
     icon: 'clear-night',
     nearestStormDistance: 34,
     nearestStormBearing: 286,
     precipIntensity: 0,
     precipProbability: 0,
     temperature: 64.62,
     apparentTemperature: 64.62,
     dewPoint: 57.76,
     humidity: 0.78,
     windSpeed: 2.23,
     windBearing: 0,
     visibility: 9.72,
     cloudCover: 0,
     pressure: 1016.21,
     ozone: 268.4 },
  minutely:
   { summary: 'Clear for the hour.',
     icon: 'clear-night',
     data:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ] },
  hourly:
   { summary: 'Clear throughout the day.',
     icon: 'clear-day',
     data:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ] },
  daily:
   { summary: 'Rain on Monday, with temperatures bottoming out at 78°F on Friday.',
     icon: 'rain',
     data:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ] },
  flags:
   { sources:
      [ 'darksky',
        'lamp',
        'gfs',
        'cmc',
        'nam',
        'rap',
        'rtma',
        'sref',
        'fnmoc',
        'isd',
        'nwspa',
        'madis',
        'nearest-precip' ],
     'darksky-stations': [ 'KCLX' ],
     'lamp-stations': [ 'KJYL', 'KLHW', 'KTBR', 'KVDI' ],
     'isd-stations':
      [ '692704-99999',
        '720301-63846',
        '720951-99999',
        '722691-99999',
        '747805-63818' ],
     'madis-stations': [ 'E8090', 'KCWV', 'KLHW', 'KSBO', 'KTBR', 'KVDI', 'MTFG1' ],
     units: 'us' },
  expires: 1475374375269 }
